### ISSUE TITLE
Motor Control does not have read property.

### ISSUE THREAD

**Issue by tetunori** [toio/toio-spec#11]
Although, [this page](https://toio.github.io/toio-spec/docs/ble_motor) (especially [this](https://toio.github.io/toio-spec/docs/ble_motor#%E8%AA%AD%E3%81%BF%E5%87%BA%E3%81%97%E6%93%8D%E4%BD%9C--%E9%80%9A%E7%9F%A5))shows that motor control characteristic has properties **read**, notify and write(woResp), it seems actual data from Cube includes properties notify and write(woResp) only.  
Actually, I could not read this characteristic.     
Could you confirm it?

**Comment by TakeshiYaeda** [comment]
@tetunori Thank you for your feedback  and sorry for my late action.

I confirmed what you say and fixed it as follows.

- for 2.0.0: `write`
- for 2.1.0: `write`, `notify`
- for 2.2.0: `write`, `notify`, `read`

BTW, v2.2.0 is released. Please try it 💃

**Comment by tetunori** [comment]
LGTM and I also confirmed that it has been fixed correctly with v2.2.0 Cube. 
Thanks for the fix!
