### ISSUE TITLE
目標指定付きモータ制御の説明のtypoについて

### ISSUE THREAD

**Issue by shimodash** [toio/toio-spec#13]
新しく説明が追加されました「目標指定付きモータ制御」の説明に
typoと思われるところを見つけました。

`目標となる状態を指定してモーターを制御し、キューブを自律的に移動させることができます。
設定する木法は以下の構成になっています。`
木法→目標かと思います。

**Comment by TakeshiYaeda** [comment]
@shimodash typoの報告ありがとうございます．修正しておきます．

**Comment by TakeshiYaeda** [comment]
@shimodash 遅くなってすみません．修正しました．ご報告ありがとうございました！
