### ISSUE TITLE
There seems to be typo in "BLE Protocol Version" data size. 

### ISSUE THREAD

**Issue by tetunori** [toio/toio-spec#17]
When I got the BLE protocol version as listed [BLE プロトコルバージョンの取得](https://toio.github.io/toio-spec/docs/ble_configuration#ble-%E3%83%97%E3%83%AD%E3%83%88%E3%82%B3%E3%83%AB%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%81%AE%E5%8F%96%E5%BE%97), I got a 5-byte string of `'2.2.0'` and could not get 6th byte character with the error `Uncaught RangeError: Offset is outside the bounds of the DataView` on the notification from WebBluetooth stack. The specification above says `6 bytes utf-8`, but I think this might be a typo of `5 bytes utf-8`. Could you confirm it?  
(My Cube version is `02.0004`)

**Comment by TakeshiYaeda** [comment]
@tetunori Thank you for your report. The test has been corrected.

**Comment by tetunori** [comment]
Thanks for your confirmation!
