### ISSUE TITLE
「姿勢角検出」の説明でのtypo

### ISSUE THREAD

**Issue by yo-to** [toio/toio-spec#20]
新しく説明が追加された「姿勢角検出」の説明でtypoと思われるところを見つけました。
https://toio.github.io/toio-spec/docs/ble_high_precision_tilt_sensor

「姿勢角情報の取得（オイラー角での通知）」の部分にある表の下、「角度」の文章で「角度の範囲は -179°(0xFF4E) から 180°(0x004B) です。」という部分、この中の2つ目のかっこの中身は180°に対応する「0x00B4」になるかと思います。

**Comment by TE-KazuhiroYabe** [comment]
ご指摘ありがとうございます。
記載にミスがありました。修正いたします。
